[package]
name = "system-constants-generator"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
description = "Tool for generating JSON files with the system constants for L1/L2 contracts"
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_state = { path = "../../lib/state", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_contracts = {path = "../../lib/contracts", version = "1.0" }
vm = {path = "../../lib/vm", version="0.1.0" }

codegen = "0.2.0"

serde = "1.0"
serde_json = "1.0"
once_cell = "1.7"
rand = { version = "0.7" }
num = { version = "0.3", features = ["serde", "rand"] }
tempfile = "3.0.2"
