[package]
name = "blob_purger"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]


[[bin]]
name = "zksync_blob_purger"
path = "src/main.rs"

[dependencies]
zksync_dal = { path = "../../lib/dal", version = "1.0" }
structopt = "0.3.26"
