[package]
name = "set_correct_tx_format_for_priority_ops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_dal = { path = "../../lib/dal", version = "1.0" }
